FROM mcr.microsoft.com/dotnet/sdk:10.0 as BUILD

RUN git clone --recurse-submodules https://github.com/GiR-Zippo/MareServers.git server

WORKDIR /server/MareSynchronosServer/MareSynchronosStaticFilesServer/

RUN dotnet publish \
        --configuration=Release \
        --os=linux \
        --output=/MareSynchronosStaticFilesServer \
        MareSynchronosStaticFilesServer.csproj

FROM mcr.microsoft.com/dotnet/aspnet:10.0

RUN useradd --system --no-create-home --user-group mare
COPY --from=BUILD /MareSynchronosStaticFilesServer /opt/MareSynchronosStaticFilesServer
RUN chown -R mare:mare /opt/MareSynchronosStaticFilesServer
RUN apt-get update && apt-get install curl -y && rm -rf /var/lib/apt/lists/*

USER mare:mare
WORKDIR /opt/MareSynchronosStaticFilesServer

CMD ["./MareSynchronosStaticFilesServer"]
