FROM mcr.microsoft.com/dotnet/sdk:10.0 as BUILD

RUN git clone --recurse-submodules https://github.com/GiR-Zippo/MareServers.git server

WORKDIR /server/MareSynchronosServer/MareSynchronosServices/

RUN dotnet publish \
        --configuration=Release \
        --os=linux \
        --output=/MareSynchronosServices \
        MareSynchronosServices.csproj

FROM mcr.microsoft.com/dotnet/aspnet:10.0

RUN useradd --system --no-create-home --user-group mare
COPY --from=BUILD /MareSynchronosServices /opt/MareSynchronosServices
RUN chown -R mare:mare /opt/MareSynchronosServices
RUN apt-get update && apt-get install curl -y && rm -rf /var/lib/apt/lists/*

USER mare:mare
WORKDIR /opt/MareSynchronosServices

CMD ["./MareSynchronosServices"]
