FROM mcr.microsoft.com/dotnet/sdk:10.0 as BUILD

RUN git clone --recurse-submodules https://github.com/GiR-Zippo/MareServers.git server

WORKDIR /server/MareSynchronosServer/MareSynchronosServer/

RUN dotnet publish \
        --configuration=Release \
        --os=linux \
        --output=/MareSynchronosServer \
        MareSynchronosServer.csproj


FROM mcr.microsoft.com/dotnet/aspnet:10.0

# Verwende useradd statt adduser
RUN useradd --system --no-create-home --user-group mare

COPY --from=BUILD /MareSynchronosServer /opt/MareSynchronosServer
RUN chown -R mare:mare /opt/MareSynchronosServer
RUN apt-get update && apt-get install curl -y && rm -rf /var/lib/apt/lists/*

USER mare:mare
WORKDIR /opt/MareSynchronosServer

CMD ["./MareSynchronosServer"]
