FROM mcr.microsoft.com/dotnet/sdk:9.0 as BUILD

COPY sourcefiles/MareAPI /sourcefiles/server/MareAPI
COPY sourcefiles/server/MareSynchronosServer/MareSynchronosShared /sourcefiles/server/MareSynchronosServer/MareSynchronosShared
COPY sourcefiles/server/MareSynchronosServer/MareSynchronosStaticFilesServer /sourcefiles/server/MareSynchronosServer/MareSynchronosStaticFilesServer

WORKDIR /sourcefiles/server/MareSynchronosServer/MareSynchronosStaticFilesServer/

RUN dotnet publish \
        --configuration=Release \
        --os=linux \
        --output=/build \
        MareSynchronosStaticFilesServer.csproj

FROM mcr.microsoft.com/dotnet/aspnet:9.0

RUN adduser \
        --disabled-password \
        --group \
        --no-create-home \
        --quiet \
        --system \
        mare

COPY --from=BUILD /build /opt/MareSynchronosStaticFilesServer
RUN chown -R mare:mare /opt/MareSynchronosStaticFilesServer
RUN apt-get update; apt-get install curl -y

USER mare:mare
WORKDIR /opt/MareSynchronosStaticFilesServer

CMD ["./MareSynchronosStaticFilesServer"]
